using System.Collections.Generic;
using Oculus.Interaction;
using UnityEngine;
using UnityEngine.Serialization;

namespace Common.Scripts
{
    public class ShoesGrabbable : PointableElement, IGrabbable
    {
        [SerializeField] private List<OnGrubEvent> onGrubEvent;
        [FormerlySerializedAs("_frame")] 
        [SerializeField] [Interface(typeof(ITransformer))] [Optional(OptionalAttribute.Flag.AutoGenerated)]
        private Object _oneGrabTransformer;

        [SerializeField] [Interface(typeof(ITransformer))] [Optional]
        private Object _twoGrabTransformer;

        [Tooltip("The target transform of the Grabbable. If unassigned, " +
                 "the transform of this GameObject will be used.")]
        [SerializeField]
        [Optional(OptionalAttribute.Flag.AutoGenerated)]
        private Transform _targetTransform;

        [SerializeField] private int _maxGrabPoints = -1;
        
        private ITransformer _activeTransformer;
        private ITransformer OneGrabTransformer;
        private ITransformer TwoGrabTransformer;
        
        public int MaxGrabPoints
        {
            get => _maxGrabPoints;
            set => _maxGrabPoints = value;
        }

        protected override void Awake()
        {
            base.Awake();
            OneGrabTransformer = _oneGrabTransformer as ITransformer;
            TwoGrabTransformer = _twoGrabTransformer as ITransformer;
        }

        protected override void Start()
        {
            this.BeginStart(ref _started, () => base.Start());

            if (_targetTransform == null) _targetTransform = transform;

            if (_oneGrabTransformer != null)
            {
                this.AssertField(OneGrabTransformer, nameof(OneGrabTransformer));
                OneGrabTransformer.Initialize(this);
            }

            if (_twoGrabTransformer != null)
            {
                this.AssertField(TwoGrabTransformer, nameof(TwoGrabTransformer));
                TwoGrabTransformer.Initialize(this);
            }

            // Create a default if no transformers assigned
            if (OneGrabTransformer == null &&
                TwoGrabTransformer == null)
            {
                var defaultTransformer = gameObject.AddComponent<OneGrabFreeTransformer>();
                _oneGrabTransformer = defaultTransformer;
                OneGrabTransformer = defaultTransformer;
                OneGrabTransformer.Initialize(this);
            }

            this.EndStart(ref _started);
        }

        protected override void OnDisable()
        {
            if (_started) EndTransform();

            base.OnDisable();
        }

        public Transform Transform => _targetTransform;
        public List<Pose> GrabPoints => _selectingPoints;

        public override void ProcessPointerEvent(PointerEvent evt)
        {
            switch (evt.Type)
            {
                case PointerEventType.Select:
                    foreach (var obj in onGrubEvent)
                    {
                        obj.OnSelect();
                    }
                    EndTransform();
                    break;
                case PointerEventType.Unselect:
                    foreach (var obj in onGrubEvent)
                    {
                        obj.OnUnselect();
                    }
                    EndTransform();
                    break;
                case PointerEventType.Cancel:
                    EndTransform();
                    break;
            }

            base.ProcessPointerEvent(evt);

            switch (evt.Type)
            {
                case PointerEventType.Select:
                    BeginTransform();
                    break;
                case PointerEventType.Unselect:
                    BeginTransform();
                    break;
                case PointerEventType.Move:
                    UpdateTransform();
                    break;
            }
        }

        // Whenever we change the number of grab points, we save the
        // current transform data
        private void BeginTransform()
        {
            // End the transform on any existing transformer before we
            // begin the new one
            EndTransform();

            var useGrabPoints = _selectingPoints.Count;
            if (_maxGrabPoints != -1) useGrabPoints = Mathf.Min(useGrabPoints, _maxGrabPoints);

            switch (useGrabPoints)
            {
                case 1:
                    _activeTransformer = OneGrabTransformer;
                    break;
                case 2:
                    _activeTransformer = TwoGrabTransformer;
                    break;
                default:
                    _activeTransformer = null;
                    break;
            }

            if (_activeTransformer == null) return;

            _activeTransformer.BeginTransform();
        }

        private void UpdateTransform()
        {
            if (_activeTransformer == null) return;

            _activeTransformer.UpdateTransform();
        }

        private void EndTransform()
        {
            if (_activeTransformer == null) return;
            _activeTransformer.EndTransform();
            _activeTransformer = null;
        }

        #region Inject

        public void InjectOptionalOneGrabTransformer(ITransformer transformer)
        {
            _oneGrabTransformer = transformer as Object;
            OneGrabTransformer = transformer;
        }

        public void InjectOptionalTwoGrabTransformer(ITransformer transformer)
        {
            _twoGrabTransformer = transformer as Object;
            TwoGrabTransformer = transformer;
        }

        public void InjectOptionalTargetTransform(Transform targetTransform)
        {
            _targetTransform = targetTransform;
        }

        #endregion
    }
}